Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Metrics/MethodLength:
  Max: 70

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
